# Generated by Django 4.2.6 on 2023-10-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(),
        ),
    ]
